/ouster/os_driver:
  ros__parameters:
    sensor_hostname: "169.254.49.182" 
    proc_mask: "RAW" # Only publish RAW packets
    lidar_port: 7502
    imu_port: 7503
    phase_lock_enable: true
    phase_lock_offset: 0